Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2022-08, with the labels that each got.

#202 bugfix: infinite diff. for burn alert and trigger pagerduty recipients if severity not specified
  docs/resources/burn_alert.md
  docs/resources/trigger.md
  honeycombio/resource_burn_alert.go
  honeycombio/resource_burn_alert_test.go
  honeycombio/resource_trigger.go
  honeycombio/resource_trigger_test.go
  honeycombio/type_helpers.go
Labels: bug

#185 [datasets] Add additional fields description and ExpandJSON Depth
  client/dataset.go
  client/dataset_test.go
  docs/resources/dataset.md
  honeycombio/resource_dataset.go
  honeycombio/resource_dataset_test.go
Labels: feature

#210 boards: add support for managing column layout
  client/board.go
  client/board_test.go
  docs/resources/board.md
  honeycombio/resource_board.go
  honeycombio/resource_board_test.go
Labels: feature

#211 boards: add support for managing query graph settings
  client/board.go
  client/board_test.go
  docs/resources/board.md
  example/board_with_annotations/main.tf
  honeycombio/resource_board.go
  honeycombio/resource_board_test.go
Labels: feature

#215 go: upgrade to 1.18
  .go-version
  go.mod
  go.sum
Labels: dependencies, go
