Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2023-12, with the labels that each got.

#412 fix: legacy api key typo
  client/client.go
Labels: bug

#414 feat(client): standardize and document API endpoint envvar
  README.md
  client/client.go
  docs/index.md
  internal/provider/burn_alert_resource_test.go
  internal/provider/trigger_resource_test.go
Labels: feature, breaking-change

#416 refactor(client) - testsuite and constructor improvements
  client/auth.go
  client/auth_test.go
  client/board.go
  client/board_test.go
  client/burn_alert.go
  client/burn_alert_test.go
  client/client.go
  client/client_test.go
  client/column.go
  client/column_test.go
  client/dataset.go
  client/dataset_definitions.go
  client/dataset_definitions_test.go
  client/dataset_test.go
  client/derived_column.go
  client/derived_column_test.go
  client/errors_test.go
  client/marker.go
  client/marker_settings.go
  client/marker_settings_test.go
  client/marker_test.go
  client/query.go
  client/query_annotation.go
  client/query_annotation_test.go
  client/query_result.go
  client/query_result_test.go
  client/query_spec.go
  client/query_spec_test.go
  client/query_test.go
  client/recipient.go
  client/recipient_test.go
  client/slo.go
  client/slo_test.go
  client/trigger.go
  client/trigger_test.go
  honeycombio/provider.go
  honeycombio/provider_test.go
  internal/provider/burn_alert_resource.go
  internal/provider/provider.go
  internal/provider/provider_test.go
Labels: refactor, breaking-change

#417 chore(ci): switch to golangci-lint and fix lints
  .github/workflows/ci.yaml
  .golangci.yml
  client/board.go
  client/client.go
  client/dataset_test.go
  client/marker.go
  client/marker_settings.go
  client/marker_settings_test.go
  client/marker_test.go
  client/query_annotation_test.go
  client/query_test.go
  client/trigger.go
  honeycombio/data_source_column.go
  honeycombio/data_source_columns.go
  honeycombio/data_source_datasets.go
  honeycombio/data_source_datasets_test.go
  honeycombio/data_source_query_result.go
  honeycombio/data_source_query_specification.go
  honeycombio/data_source_recipient.go
  honeycombio/data_source_recipient_test.go
  honeycombio/data_source_recipients.go
  honeycombio/internal/verify/json.go
  honeycombio/internal/verify/query_spec.go
  honeycombio/provider.go
  honeycombio/provider_test.go
  honeycombio/query_spec.go
  honeycombio/resource_board.go
  honeycombio/resource_board_test.go
  honeycombio/resource_column.go
  honeycombio/resource_dataset.go
  honeycombio/resource_dataset_definition.go
  honeycombio/resource_dataset_definition_test.go
  honeycombio/resource_derived_column.go
  honeycombio/resource_email_recipient.go
  honeycombio/resource_marker.go
  honeycombio/resource_marker_setting.go
  honeycombio/resource_msteams_recipient.go
  honeycombio/resource_pagerduty_recipient.go
  honeycombio/resource_query.go
  honeycombio/resource_query_annotation.go
  honeycombio/resource_query_test.go
  honeycombio/resource_slack_recipient.go
  honeycombio/resource_slo.go
  honeycombio/resource_webhook_recipient.go
  internal/helper/validation/divisible_by_test.go
  internal/helper/validation/precision_at_most.go
  internal/helper/validation/precision_at_most_test.go
  internal/helper/validation/valid_regex_test.go
  internal/provider/burn_alert_resource.go
  internal/provider/burn_alert_resource_test.go
  internal/provider/derived_columns_data_source_test.go
  internal/provider/provider.go
  internal/provider/trigger_resource.go
Labels: improvement
