Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2023-11, with the labels that each got.

#386 Add support for 'msteams' recipients
  client/recipient.go
  client/recipient_test.go
  docs/data-sources/recipient.md
  docs/data-sources/recipients.md
  docs/resources/burn_alert.md
  docs/resources/msteams_recipient.md
  docs/resources/trigger.md
  honeycombio/data_source_recipient.go
  honeycombio/data_source_recipient_test.go
  honeycombio/data_source_recipients.go
  honeycombio/provider.go
  honeycombio/resource_msteams_recipient.go
  honeycombio/resource_recipients_test.go
  honeycombio/type_helpers.go
  internal/provider/burn_alert_resource.go
  internal/provider/notification_recipients.go
  internal/provider/trigger_resource.go
Labels: feature

#387 maint: prune dead code and tidy up
  client/column.go
  client/query_spec.go
  client/type_helpers_test.go
  honeycombio/data_source_column_test.go
  honeycombio/data_source_columns_test.go
  honeycombio/data_source_query_specification.go
  honeycombio/data_source_recipient_test.go
  honeycombio/data_source_recipients_test.go
  honeycombio/data_source_trigger_recipient.go
  honeycombio/data_source_trigger_recipient_test.go
  honeycombio/helpers_test.go
  honeycombio/resource_board.go
  honeycombio/resource_column.go
  honeycombio/resource_query_annotation_test.go
  honeycombio/resource_recipients_test.go
  honeycombio/resource_slo_test.go
  honeycombio/type_helpers.go
  honeycombio/type_helpers_test.go
  internal/provider/slos_data_source_test.go
  internal/provider/trigger_resource_test.go
Labels: refactor, improvement

#388 stage 0.19.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog

#392 client: Fix bug where API errors weren't including the field or getting separated
  client/errors.go
  client/errors_test.go
Labels: bug

#395 stage 0.20.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog

#398 fix(slo, burn_alert, client) missing resources shouldn't error but be recreated
  client/errors.go
  honeycombio/resource_slo.go
  honeycombio/resource_slo_test.go
  internal/provider/burn_alert_resource.go
  internal/provider/burn_alert_resource_test.go
  internal/provider/trigger_resource.go
Labels: bug

#401 chore: first pass at moving away from pre-created columns
  client/auth_test.go
  client/board_test.go
  client/burn_alert_test.go
  client/client_test.go
  client/column_test.go
  client/dataset_definitions.go
  client/dataset_definitions_test.go
  client/dataset_test.go
  client/derived_column_test.go
  client/errors_test.go
  client/marker_settings_test.go
  client/marker_test.go
  client/query_annotation_test.go
  client/query_result_test.go
  client/query_spec_test.go
  client/query_test.go
  client/recipient_test.go
  client/slo_test.go
  client/trigger_test.go
  client/type_helpers_test.go
  honeycombio/resource_dataset_definition_test.go
  internal/helper/test/strings.go
Labels: improvement

#400 fix(honeycombio_board) graph_settings should revert to false when removed
  client/board.go
  honeycombio/resource_board.go
  honeycombio/resource_board_test.go
Labels: bug

#402 stage 0.20.1
  CHANGELOG.md
Labels: no-changelog

#404 fix(client) - queryspec Granularity equivalency
  client/query_spec.go
  client/query_spec_test.go
Labels: bug

#405 stage 0.20.2
  CHANGELOG.md
Labels: no-changelog
