Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2024-10, with the labels that each got.

#554 fix: column-related test flakes
  honeycombio/resource_column_test.go
  honeycombio/resource_derived_column_test.go
Labels: bug

#558 feat(d/query_specification): local-only datasource
  internal/provider/query_specification_data_source.go
Labels: feature

#559 chore: r/dataset_definition - add log_severity and log_message
  client/dataset_definitions.go
  client/dataset_definitions_test.go
  docs/resources/dataset_definitions.md
  honeycombio/resource_dataset_definition.go
Labels: feature

#560 chore(ci): notify in Slack if scheduled CI run fails
  .github/workflows/ci.yaml
Labels: no-changelog

#561 rel: 0.27.2
  CHANGELOG.md
Labels: no-changelog
