Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2024-12, with the labels that each got.

#586 feat: webhook headers
  client/recipient.go
  client/recipient_test.go
  docs/resources/webhook_recipient.md
  internal/models/recipients.go
  internal/provider/webhook_recipient_resource.go
  internal/provider/webhook_recipient_resource_test.go
Labels: feature

#587 chore(ci): increase integration test timeout to 20min
  .github/workflows/ci.yaml
Labels: refactor

#588 chore(ci): remove codecov
  .github/workflows/ci.yaml
  README.md
Labels: refactor

#593 fix(r/trigger): handle state error with equivalent query_json
  internal/provider/trigger_resource.go
  internal/provider/trigger_resource_test.go
Labels: bug

#595 rel: 0.28.2
  CHANGELOG.md
Labels: no-changelog
