Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2024-09, with the labels that each got.

#539 fix(r/trigger): handle dynamic evaluation schedule
  internal/models/notification_recipients.go
  internal/models/triggers.go
  internal/provider/notification_recipients.go
  internal/provider/trigger_resource.go
  internal/provider/trigger_resource_test.go
Labels: bug

#538 chore(docs): standardize use of notes
  docs/data-sources/column.md
  docs/data-sources/derived_column.md
  docs/data-sources/environment.md
  docs/data-sources/environments.md
  docs/data-sources/query_result.md
  docs/data-sources/recipient.md
  docs/data-sources/trigger_recipient.md
  docs/resources/api_key.md
  docs/resources/column.md
  docs/resources/dataset.md
  docs/resources/dataset_definitions.md
  docs/resources/environment.md
  docs/resources/marker.md
  docs/resources/marker_setting.md
  docs/resources/msteams_recipient.md
  docs/resources/query.md
  docs/resources/query_annotation.md
Labels: improvement

#540 feat: slack channel regex accepts channel id
  docs/resources/slack_recipient.md
  honeycombio/resource_slack_recipient.go
Labels: improvement

#541 rel: v0.27.1
  CHANGELOG.md
Labels: no-changelog

#542 chore: bump Go to 1.22
  .go-version
  .golangci.yml
  client/v2/api_keys_test.go
  client/v2/environments_test.go
  go.mod
  internal/helper/validation/divisible_by_test.go
  internal/helper/validation/precision_at_most_test.go
  internal/helper/validation/query_spec_test.go
  internal/helper/validation/valid_regex_test.go
  internal/provider/datasets_data_source_test.go
  internal/provider/environments_data_source_test.go
Labels: dependencies

#546 chore(go): fix go version
  go.mod
Labels: dependencies

#547 fix(r/derived_column): tidy up test
  honeycombio/resource_derived_column_test.go
Labels: improvement

#548 fix(d/column): fix failing d/column test and tidy up
  honeycombio/data_source_column_test.go
  honeycombio/data_source_columns_test.go
  honeycombio/helpers_test.go
Labels: bug

#549 fix: generate random URLs for webhook-like recipients
  client/marker_test.go
  client/recipient_test.go
  honeycombio/data_source_recipient_test.go
  honeycombio/recipients_test.go
  internal/helper/test/strings.go
Labels: bug
