Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2024-08, with the labels that each got.

#520 fix(limits): separately test min-max vs header+jitter cases
  client/v2/limits_test.go
Labels: bug

#521 chore(r/query): add doc note about using latest derived column definition
  docs/resources/query.md
Labels: improvement

#522 chore(ci): add environment sweeper
  internal/provider/api_key_resource_test.go
  internal/provider/honeycombio_sweeper_test.go
  internal/provider/provider_test.go
  internal/provider/query_resource_test.go
  internal/provider/trigger_resource_test.go
Labels: improvement

#525 fix: environments data source test flake
  internal/provider/environments_data_source_test.go
Labels: improvement

#526 chore: improve V2 API error reporting
  client/errors.go
  client/errors_test.go
  client/v2/client_test.go
  go.mod
  go.sum
Labels: improvement

#529 rel: v0.26.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog

#532 chore: address new linter errors
  client/burn_alert_test.go
  client/v2/client.go
  client/v2/limits.go
  client/v2/limits_test.go
  internal/helper/validation/precision_at_most.go
Labels: bug

#531 chore(r/query): improve doc for derived_column
  docs/resources/query.md
Labels: bug

#535 feat: full lifecycle support for datasets
  client/client.go
  client/dataset.go
  client/dataset_test.go
  client/v2/api_keys.go
  client/v2/environments.go
  docs/data-sources/dataset.md
  docs/data-sources/datasets.md
  docs/resources/dataset.md
  honeycombio/data_source_datasets.go
  honeycombio/data_source_datasets_test.go
  honeycombio/provider.go
  honeycombio/resource_dataset.go
  honeycombio/resource_dataset_test.go
  internal/helper/modifiers/deletion_protection.go
  internal/models/datasets.go
  internal/provider/dataset_data_source.go
  internal/provider/dataset_data_source_test.go
  internal/provider/dataset_resource.go
  internal/provider/dataset_resource_test.go
  internal/provider/datasets_data_source.go
  internal/provider/datasets_data_source_test.go
  internal/provider/environment_data_source.go
  internal/provider/environments_data_source_test.go
  internal/provider/honeycombio_sweeper_test.go
  internal/provider/provider.go
Labels: feature, breaking-change

#536 rel: 0.27.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog
