Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2024-11, with the labels that each got.

#563 feat: add support for burn alert description
  client/burn_alert.go
  client/burn_alert_test.go
  docs/resources/burn_alert.md
  internal/models/burn_alerts.go
  internal/provider/burn_alert_resource.go
  internal/provider/burn_alert_resource_test.go
Labels: feature

#566 fix(docs): incorrect formatting trigger example
  docs/resources/trigger.md
Labels: bug

#572 chore(ci): remove paths-ignore from CI workflow
  .github/workflows/ci.yaml
Labels: no-changelog

#574 rel: v0.28.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog

#575 fix(r/burn_alert): handle existing remote description with default description value
  client/burn_alert.go
  internal/provider/burn_alert_resource_test.go
Labels: bug

#577 chore: tidy up lint config
  .golangci.yml
  client/board_test.go
  client/burn_alert_test.go
  client/column_test.go
  client/slo_test.go
  honeycombio/data_source_recipient_test.go
  honeycombio/data_source_recipients_test.go
  honeycombio/data_source_trigger_recipient_test.go
  honeycombio/resource_board_test.go
  honeycombio/resource_slo.go
  honeycombio/resource_slo_test.go
  internal/provider/burn_alert_resource_test.go
  internal/provider/dataset_resource_test.go
  internal/provider/derived_column_data_source_test.go
  internal/provider/derived_columns_data_source_test.go
  internal/provider/slo_data_source_test.go
  internal/provider/slos_data_source_test.go
  internal/provider/trigger_resource_test.go
  internal/provider/webhook_recipient_resource_test.go
Labels: refactor

#580 feat: webhook payloads templates on honeycombio_webhook_recipient
  CONTRIBUTING.md
  client/recipient.go
  client/recipient_test.go
  docs/resources/webhook_recipient.md
  internal/models/recipients.go
  internal/provider/webhook_recipient_resource.go
  internal/provider/webhook_recipient_resource_test.go
Labels: feature

#585 feat(Board, SLO): Bump up max number of SLOs on a board to 24
  honeycombio/resource_board.go
Labels: feature

#583 feat: template variables
  client/recipient.go
  client/recipient_test.go
  docs/resources/webhook_recipient.md
  internal/models/recipients.go
  internal/provider/webhook_recipient_resource.go
  internal/provider/webhook_recipient_resource_test.go
Labels: feature
