Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2024-07, with the labels that each got.

#496 feat: key management support
  .github/workflows/ci.yaml
  client/client.go
  client/errors.go
  client/errors_test.go
  client/v2/api_keys.go
  client/v2/api_keys_test.go
  client/v2/client.go
  client/v2/client_test.go
  client/v2/models.go
  client/v2/pagination.go
  client/v2/pagination_test.go
  docs/index.md
  docs/resources/api_key.md
  go.mod
  go.sum
  honeycombio/data_source_column.go
  honeycombio/data_source_columns.go
  honeycombio/data_source_datasets.go
  honeycombio/data_source_query_result.go
  honeycombio/data_source_recipient.go
  honeycombio/data_source_recipients.go
  honeycombio/data_source_trigger_recipient.go
  honeycombio/provider.go
  honeycombio/resource_board.go
  honeycombio/resource_column.go
  honeycombio/resource_dataset.go
  honeycombio/resource_dataset_definition.go
  honeycombio/resource_derived_column.go
  honeycombio/resource_marker.go
  honeycombio/resource_marker_setting.go
  honeycombio/resource_query_annotation.go
  honeycombio/resource_slo.go
  honeycombio/type_helpers.go
  internal/helper/diag.go
  internal/helper/validation/divisible_by_test.go
  internal/helper/validation/precision_at_most_test.go
  internal/helper/validation/query_spec_test.go
  internal/helper/validation/valid_regex_test.go
  internal/models/api_keys.go
  internal/provider/api_key_resource.go
  internal/provider/api_key_resource_test.go
  internal/provider/auth_metadata_data_source.go
  internal/provider/burn_alert_resource.go
  internal/provider/derived_column_data_source.go
  internal/provider/derived_columns_data_source.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/query_resource.go
  internal/provider/query_specification_data_source.go
  internal/provider/slo_data_source.go
  internal/provider/slos_data_source.go
  internal/provider/trigger_resource.go
Labels: feature

#498 chore(go): add missing toolchain directive
  .go-version
  go.mod
Labels: dependencies

#500 fix: incorrect conversion between integer types
  honeycombio/type_helpers.go
  honeycombio/type_helpers_test.go
Labels: bug

#502 chore: cleanup static environment ID in favour of new functionality
  .github/workflows/ci.yaml
  client/v2/api_keys_test.go
  client/v2/client_test.go
  internal/provider/api_key_resource_test.go
  internal/provider/environment_data_source_test.go
  internal/provider/environments_data_source_test.go
  internal/provider/provider_test.go
Labels: refactor

#503 chore: refresh README and CONTRIBUTING docs
  .env
  CONTRIBUTING.md
  README.md
Labels: improvement

#505 fix: read of null definition causes panic (#504)
  honeycombio/resource_dataset_definition.go
  honeycombio/resource_dataset_definition_test.go
  scripts/setup-testsuite-dataset
Labels: bug

#510 fix: temporarily disable broken r/query test
  internal/provider/query_resource_test.go
Labels: bug

#513 chore: limit integration test concurrency
  .github/workflows/ci.yaml
Labels: improvement

#514 fix: allow auto ('0') granularity
  client/v2/client.go
  internal/provider/query_specification_data_source.go
  internal/provider/query_specification_data_source_test.go
Labels: bug

#516 chore: add recipients sweeper
  .github/workflows/ci.yaml
  .golangci.yml
  Makefile
  client/burn_alert_test.go
  client/query_annotation_test.go
  client/recipient_test.go
  client/v2/api_keys_test.go
  honeycombio/data_source_recipient_test.go
  honeycombio/data_source_trigger_recipient_test.go
  honeycombio/resource_recipients_test.go
  internal/helper/test/strings.go
  internal/provider/burn_alert_resource_test.go
  internal/provider/honeycombio_sweeper_test.go
  internal/provider/query_resource_test.go
  internal/provider/trigger_resource_test.go
Labels: improvement

#517 chore(ci): display test summary output
  .github/workflows/ci.yaml
  .gitignore
Labels: improvement
