Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2024-02, with the labels that each got.

#433 fix(recipients): better handle the case where a recipient is modified outside of Terraform
  internal/provider/burn_alert_resource.go
  internal/provider/burn_alert_resource_test.go
  internal/provider/notification_recipients.go
  internal/provider/notification_recipients_test.go
  internal/provider/trigger_resource.go
  internal/provider/trigger_resource_test.go
Labels: bug

#435 rel: stage v0.21.1
  CHANGELOG.md
Labels: no-changelog

#437 fix: handle column and derived column imports with slashes in the name
  client/client_test.go
  honeycombio/resource_column.go
  honeycombio/resource_derived_column.go
  honeycombio/resource_slo.go
  internal/provider/burn_alert_resource.go
  internal/provider/trigger_resource.go
Labels: bug

#438 rel: v0.21.2
  CHANGELOG.md
Labels: no-changelog

#439 fix: query specification - always treat 'in','not-in' filter values as an array
  honeycombio/data_source_query_specification.go
  honeycombio/data_source_query_specification_test.go
Labels: bug

#444 fix(recipients): dynamic block bug
  internal/models/burn_alerts.go
  internal/models/notification_recipients.go
  internal/models/triggers.go
  internal/provider/burn_alert_resource.go
  internal/provider/burn_alert_resource_test.go
  internal/provider/notification_recipients.go
  internal/provider/notification_recipients_test.go
  internal/provider/trigger_resource.go
Labels: bug

#447 build: bump Go to 1.21
  .go-version
  client/marker_settings_test.go
  go.mod
  go.sum
  honeycombio/resource_dataset_definition_test.go
  internal/provider/notification_recipients.go
Labels: dependencies

#448 rel: v0.22.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog
