Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2025-06, with the labels that each got.

#694 feat(r/flexible_board): add support for tags on Boards
  client/board.go
  client/board_test.go
  client/trigger.go
  client/trigger_test.go
  docs/resources/flexible_board.md
  docs/resources/trigger.md
  internal/models/flexible_board.go
  internal/provider/flexible_board_resource.go
  internal/provider/flexible_board_resource_test.go
Labels: feature

#686 fix(client): use proper format for Retry-After fallback
  client/internal/limits/limits.go
  client/internal/limits/limits_test.go
Labels: bug

#693 chore(docs): clarify that dataset and datasets field of slos expect slugs
  docs/index.md
Labels: improvement

#689 feat: Enhance `detail_filter` support for multi-value and multi-filter
  docs/data-sources/datasets.md
  docs/data-sources/environment.md
  docs/data-sources/environments.md
  docs/data-sources/slos.md
  honeycombio/type_helpers.go
  honeycombio/type_helpers_test.go
  internal/helper/coerce/coerce.go
  internal/helper/coerce/coerce_test.go
  internal/helper/filter/detail_filter.go
  internal/helper/filter/detail_filter_group.go
  internal/helper/filter/detail_filter_group_test.go
  internal/helper/filter/detail_filter_test.go
  internal/models/datasets.go
  internal/models/detail_filter.go
  internal/models/environments.go
  internal/models/slo.go
  internal/provider/datasets_data_source.go
  internal/provider/detail_filter.go
  internal/provider/environment_data_source.go
  internal/provider/environments_data_source.go
  internal/provider/query_specification_data_source.go
  internal/provider/slos_data_source.go
  internal/provider/slos_data_source_test.go
Labels: feature

#705 fix(tags): handle empty tags map
  internal/helper/tags.go
  internal/provider/slo_resource_test.go
  internal/provider/tags.go
Labels: bug
