Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2025-03, with the labels that each got.

#629 feat(client): improve V1 api client retry behaviour
  client/client.go
  client/internal/limits/limits.go
  client/internal/limits/limits_test.go
  client/v2/client.go
Labels: feature

#632 rel: v0.31.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog

#635 feat(slo): add md slo support for slo data source
  client/client.go
  client/slo.go
  client/slo_test.go
  docs/data-sources/slo.md
  docs/data-sources/slos.md
  internal/models/slo.go
  internal/provider/slo_data_source.go
  internal/provider/slo_data_source_test.go
Labels: feature

#638 chore(ci): don't highlight skipped tests
  .github/workflows/ci.yaml
Labels: improvement

#642 feat(d/query_specification): 'order' validation support
  internal/provider/query_specification_data_source.go
  internal/provider/query_specification_data_source_test.go
Labels: feature
