Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2025-04, with the labels that each got.

#648 chore(r/webhook_recipient): increase header value char limit
  internal/provider/webhook_recipient_resource.go
Labels: feature

#644 feat(r/burn_alert): add multi-dataset support
  docs/resources/burn_alert.md
  docs/resources/slo.md
  honeycombio/resource_slo.go
  honeycombio/resource_slo_test.go
  internal/helper/dataset.go
  internal/helper/modifiers/dataset_deprecation.go
  internal/provider/burn_alert_resource.go
  internal/provider/burn_alert_resource_test.go
Labels: feature

#649 maint(deps): bump Go from 1.23.6 to 1.23.8
  .go-version
  go.mod
Labels: dependencies

#652 fix(build): remove incorrect 'toolchain' directive
  go.mod
Labels: bug

#655 fix(r/trigger): adjust frequency<>duration validation error message for clarity
  internal/provider/trigger_resource.go
  internal/provider/trigger_resource_test.go
Labels: bug

#654 feat: remove need for magic environment-wide string
  docs/data-sources/derived_column.md
  docs/data-sources/derived_columns.md
  docs/data-sources/query_result.md
  docs/resources/derived_column.md
  docs/resources/marker.md
  docs/resources/marker_setting.md
  docs/resources/query.md
  docs/resources/query_annotation.md
  docs/resources/slo.md
  honeycombio/data_source_query_result.go
  honeycombio/data_source_query_result_test.go
  honeycombio/internal/verify/dataset.go
  honeycombio/resource_derived_column.go
  honeycombio/resource_derived_column_test.go
  honeycombio/resource_marker.go
  honeycombio/resource_marker_setting.go
  honeycombio/resource_marker_setting_test.go
  honeycombio/resource_marker_test.go
  honeycombio/resource_query_annotation.go
  honeycombio/resource_query_annotation_test.go
  honeycombio/resource_slo.go
  honeycombio/type_helpers.go
  internal/helper/dataset.go
  internal/helper/modifiers/dataset_deprecation.go
  internal/provider/burn_alert_resource.go
  internal/provider/burn_alert_resource_test.go
  internal/provider/derived_column_data_source.go
  internal/provider/derived_column_data_source_test.go
  internal/provider/derived_columns_data_source.go
  internal/provider/derived_columns_data_source_test.go
  internal/provider/query_resource.go
  internal/provider/query_resource_test.go
  internal/provider/slo_data_source.go
Labels: feature

#656 rel: v0.32.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog

#659 chore(r/board): migrate to Plugin Framework
  docs/resources/board.md
  honeycombio/provider.go
  honeycombio/resource_board.go
  internal/models/boards.go
  internal/provider/board_resource.go
  internal/provider/board_resource_test.go
  internal/provider/provider.go
Labels: improvement

#660 feat(d/environment): add detail_filter to simplify environment lookup
  docs/data-sources/environment.md
  internal/models/environments.go
  internal/provider/environment_data_source.go
  internal/provider/environment_data_source_test.go
Labels: feature

#658 feat(r/trigger): add baseline_details support
  client/trigger.go
  client/trigger_test.go
  docs/resources/trigger.md
  example/trigger_with_baseline_details/main.tf
  internal/models/triggers.go
  internal/provider/trigger_resource.go
  internal/provider/trigger_resource_test.go
Labels: feature

#661 feat(r/api_key): add computed 'key' field
  client/v2/api_keys_test.go
  docs/resources/api_key.md
  internal/models/api_keys.go
  internal/provider/api_key_resource.go
  internal/provider/api_key_resource_test.go
Labels: feature

#663 feat(d/query_specification): temporary calculated field support
  client/query_spec.go
  client/query_spec_test.go
  docs/data-sources/query_specification.md
  internal/helper/validation/valid_calculated_field.go
  internal/helper/validation/valid_calculated_field_test.go
  internal/models/query.go
  internal/provider/query_specification_data_source.go
  internal/provider/query_specification_data_source_test.go
Labels: feature

#664 rel: v0.33.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog

#665 fix(r/trigger,r/burn_alert): gracefully handle recipients with notification details on import
  internal/provider/burn_alert_resource.go
  internal/provider/notification_recipients.go
  internal/provider/notification_recipients_test.go
  internal/provider/trigger_resource.go
Labels: bug
