Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2025-07, with the labels that each got.

#710 fix(r/slo): SLO update causing resource replacement
  internal/helper/modifiers/datasets_require_replace.go
  internal/provider/slo_resource.go
  internal/provider/slo_resource_test.go
Labels: bug

#711 rel: v0.36.2
  CHANGELOG.md
Labels: no-changelog

#717 chore(tags): increase tag Value max length to 128
  client/tags.go
  client/tags_test.go
  internal/provider/tags.go
Labels: improvement

#718 rel: v0.37.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog

#721 fix(r/flexible_board): Remove height limit
  internal/provider/flexible_board_resource.go
Labels: bug

#720 Accommodate the "dataset_slug" field in triggers
  client/trigger.go
  client/trigger_test.go
Labels: bug

#724 fix(client): add missing Dataset field to QueryPanel
  client/board.go
  client/board_test.go
  internal/provider/honeycombio_sweeper_test.go
Labels: feature
