Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2025-05, with the labels that each got.

#671 chore(ci): fix CI status badge
  README.md
Labels: bug

#667 feat(d/slo,r/slo): add 'tags' support
  client/slo.go
  client/slo_test.go
  client/tags.go
  client/tags_test.go
  docs/data-sources/slo.md
  docs/resources/slo.md
  example/slo_with_burn_alert/main.tf
  honeycombio/resource_slo.go
  honeycombio/resource_slo_test.go
  internal/models/slo.go
  internal/provider/slo_data_source.go
  internal/provider/slo_data_source_test.go
Labels: feature

#677 feat(boards): Add flexible board resource
  client/board.go
  client/board_test.go
  docs/resources/flexible_board.md
  example/flexible_board/main.tf
  internal/models/flexible_board.go
  internal/provider/flexible_board_resource.go
  internal/provider/flexible_board_resource_test.go
  internal/provider/provider.go
Labels: feature

#679 rel: v0.35.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog

#682 chore(r/slo): migrate SLO resource to Plugin Framework
  honeycombio/provider.go
  honeycombio/resource_slo.go
  internal/helper/dataset.go
  internal/helper/modifiers/equivalent_tags.go
  internal/helper/tags.go
  internal/models/slo.go
  internal/provider/provider.go
  internal/provider/slo_resource.go
  internal/provider/slo_resource_test.go
Labels: refactor
