Repository honeycombio/terraform-provider-honeycombio, pull requests merged in 2025-01, with the labels that each got.

#594 feat(webhook recipient): notification variables
  client/recipient.go
  docs/data-sources/recipient.md
  docs/resources/burn_alert.md
  docs/resources/trigger.md
  internal/helper/validation/valid_notification_variables.go
  internal/models/notification_recipients.go
  internal/provider/burn_alert_resource_test.go
  internal/provider/notification_recipients.go
  internal/provider/notification_recipients_test.go
  internal/provider/trigger_resource_test.go
Labels: feature

#598 rel: v0.29.0
  CHANGELOG.md
  README.md
  docs/index.md
Labels: no-changelog

#599 fix(ci): extend 'go test' timeout to 20 min
  .github/workflows/ci.yaml
  .github/workflows/validate-examples.yml
Labels: bug

#601 fix: update query annotation name and description max length to reflect recent api change
  CONTRIBUTING.md
  honeycombio/resource_query_annotation.go
Labels: bug
